services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT:-8087}:8000"
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  django-cli:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    command: python manage.py fibonacci "2026-06-01 00:00:00" "2026-06-30 23:59:59"
